#!/bin/bash

if [ $1 == '-n' ]; then
	dec=$2
	enc=$2.enc
	printf "Введите парольную фразу: "
	read -s pass
	printf "***\n"
	openssl aes-128-cbc -e -in $dec -out $enc -k $pass
	if [ $? -ne 0 ]; then
		echo "Unnown error"
		exit 1
	fi
	cp $enc $dec
	rm $enc
else
	enc=$1
	dec=$1.dec
	printf "Введите парольную фразу: "
	read -s pass
	printf "***\n"
	openssl aes-128-cbc -d -in $enc -out $dec -k $pass 2>/dev/null
	if [ $? -ne 0 ]; then
		echo "Incorrect password"
		exit 1
	fi
	editor $dec
	openssl aes-128-cbc -e -in $dec -out $enc -k $pass
	if [ $? -ne 0 ]; then
		echo "Unnown error"
		exit 1
	fi
	rm $dec
fi
